apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-cb
  namespace: cinjith
  annotations:
    kubernetes.io/change-cause: "Revision two"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web1
  template:
    metadata:
      labels:
        app: web1
    spec:
      containers:
      - name: c1
        image: cinjith/docker_repo:52224b3bbd26a8f7e9b212d6faa7d0dc3a1a9353

