apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-cb
  namespace: cinjith
  annotations:
    kubernetes.io/change-cause: "Revision two"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: c1
        image: cinjith/docker_repo:7d9e2c7f091692f9fa5d65b9402f442c275032dc
    
