apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-cb
  namespace: cinjith
  annotations:
    kubernetes.io/change-cause: "Revision two"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: c1
        image: cinjith/docker_repo:f94160968f4e15a22cb7a92fcca960d39230db9a
      - name: name: c2
       image: cinjith/docker_repo:f94160968f4e15a22cb7a92fcca960d39230db9a
